[dcity.d]
buildflags = -IC:\andre\desenv\D\dmd2\src\ext -debug -g -w
[gui]
buildflags = -IC:\andre\desenv\D\dmd2\src\ext -debug -g -w
[city]
buildflags = -IC:\andre\desenv\D\dmd2\src\ext -debug -g -w

