#!/usr/bin/python3

from context import *
from optparse import OptionParser
import sys

#
# parse arguments
#
prs = OptionParser(version='%prog 0.1',
                   description='[fccax] builds a world map.')
prs.add_option('-w', '--width', type='int', default=40)
prs.add_option('-g', '--height', type='int', default=40)
(options, args) = prs.parse_args()

#
# build world
#
ct = Context(options.width, options.height)
for x in range(3, 6):
    for y in range(3, 6):
        ct.map[y][x] = 'G'
ct.print(sys.stdout)
