#!/usr/bin/python3

from context import *
from optparse import OptionParser
import sys

# parse arguments
prs = OptionParser(version='%prog 0.1 [name]',
                   description='[fccax] add a nation to the game.')
(options, args) = prs.parse_args()

if len(args) != 1:
    prs.print_help()
    exit

# input context
ct = Context(sys.stdin)

# add the new nation
nation = Nation(args[0])
nation.units[0] = Unit()
ct.nations.append(nation)

# output context
ct.print(sys.stdout)
