#!/usr/bin/env lua

package.path = package.path .. ';./libchar/?.lua;./libchar/?.dll;./game/?.lua;./ui/?.lua'
require 'libchar/libchar'
require 'game'
require 'ui/map'

-- parameters
colors = true
screen_w = 80
screen_h = 50

-- initialize screen
ch.init(80, 50, 'Fertile Crescent 0.1')
if colors then
   ch.bg('black')
else
   ch.bg('white')
end
ch.clear()
ch.flush()


-- initialize game
game = Game:new(30, 30, 'Assyria')

-- initialize gui
map.init()

-- main loop
state = 'map'
running = true
while running do
   if state == 'map' then
      map.draw()
      running = map.events()
   else
      error(_'Invalid state ' .. state)
   end
end

os.exit()
