#!/usr/bin/env lua

package.path = package.path .. ';./libchar/?.lua;./libchar/?.dll;./game/?.lua;./ui/?.lua'
require 'libchar/libchar'
require 'game'
require 'ui/map'

-- parameters
colors = false
screen_w = 80
screen_h = 50

-- initialize screen
ch.init(80, 50, 'Fertile Crescent 0.1')
if colors then
   ch.bg('black')
else
   ch.bg('white')
end

ch.clear()
ch.flush()

-- initialize game
game = Game:new(30, 30, 'Assyria')
if color then
   game.player.color = 'red'
else
   game.player.color = 'lighter_gray'
end

-- initialize gui
map.init()

-- main loop
state = 'map'
running = true
while running do
   if state == 'map' then
      local ms = ch.elapsed_ms() + 10
      map.draw()
      running = map.events()
      while ch.elapsed_ms() < ms do ch.sleep(5) end
   else
      error(_'Invalid state ' .. state)
   end
end
os.exit()
