general {
        colors = true
        interval = 1
}

order += "battery 0"
order += "disk /"
order += "disk /home"
order += "wireless wlp3s0"
order += "cpu_usage"
order += "cpu_temperature 0"
order += "volume master"
order += "time"

time {
        format = "%d/%m/%Y %H:%M"
}

load {
        format = "%1min"
}

battery 0 {
	format = "%status"
	low_threshold = 90
}

disk "/" {
        format = "[/ %free]"
}

disk "/home" {
        format = "[/home %free]"
}

wireless wlp3s0 {
	format_up = "%essid (%quality)"
	format_down = "WIFI DOWN"
}

cpu_usage {
	format = "CPU %usage"
}

cpu_temperature 0 {
	format = "T: %degrees °C"
}

volume master {
	format = "♪ %volume"
	device = "default"
	mixer = "Master"
	mixer_idx = 0
}
