general {
        colors = true
        interval = 5
}

order += "cpu_usage"
order += "time"

time {
        format = "%d/%m/%Y %H:%M"
}

load {
        format = "%1min"
}

disk "/" {
        format = "%free (or: %percentage_used used, %percentage_used_of_avail used of avail, %percentage_free free, %percentage_avail avail)"
}

cpu_usage {
	format = "%usage"
}
