#!/usr/bin/ruby
# encoding: utf-8

require 'pp'

#
# classe do autômato
#
class AFND

  #
  # carrega a máquina, verifica erros e inicializa
  #
  def initialize(m)
    @deterministico = false

    # estados
    raise if not m[:K].is_a? Array
    @estados = {}
    m[:K].each { |e| raise 'Utilize apenas estados de um caractere, por favor.' if e.length != 1 }
    m[:K].each { |e| @estados[e] = Estado.new(e) }
    
    # alfabeto
    raise if not m[:S].is_a? Array or m[:S].empty?
    @alfabeto = []
    m[:S].each { |el| @alfabeto << el.to_s }

    # função de transição
    raise if not m[:d].is_a? Array
    @transicao = m[:d]
    @transicao.each do |funcao|
      raise 'Função de transição em formato incorreto.' if not funcao.is_a? Array or funcao.length != 3
      if not @estados.include? funcao[0]
        raise 'Estado da função de transição não está na lista de estados.'
      elsif not @alfabeto.include? funcao[1].to_s and funcao[1] != nil
        raise 'Estado da função de transição não está no alfabeto.'
      elsif not funcao[2].is_a? Array
        raise 'Destino da função de transição deve ser um conjunto.'
      end
      @estados[funcao[0]].proximo[funcao[1].to_s] = @estados[funcao[2]]
    end

    # estado inicial
    raise 'Só pode haver um estado inicial.' if m[:s].is_a? Array
    raise 'Estado inicial não está na lista de estados.' if not @estados.include? m[:s]
    @atual = @estados[m[:s]]

    # estados finais
    @finais = []
    raise if not m[:F].is_a? Array
    m[:F].each do |e|
      raise 'Estado final não está na lista de estados.' if not @estados.include? e
      @estados[e].final = true
      @finais << e
    end      
  end

  # 
  # converte AFND para AFD
  #
  def converte
    # estados
    estados = ['q']
    1.upto(@estados.length) do |i|
      @estados.keys.combination(i).to_a.collect { |c| c.sort.join }.each do |a|
        estados << 'q' + a
      end
    end

    # alfabeto
    alfabeto = @alfabeto

    # função de transição
    transicao = []
    estados.each do |estado|
      if estado == 'q' # vazio
        alfabeto.each { |el| transicao << [ 'q', el, 'q' ] }
      else
        alfabeto.each do |el|
          # verifica setas
          setas = []
          estado[1,estado.length].each_char do |c|
            @transicao.each do |funcao|
              if funcao[0] == c and funcao[1] == el
                setas << funcao[2]
              end
            end
          end
          setas = setas.flatten.uniq.sort
          # adiciona setas no caso de 'e'
          setas.each do |c|
            @transicao.each do |funcao|
              if funcao[0] == c and funcao[1] == nil
                setas << funcao[2]
              end
            end
          end
          setas = setas.flatten.uniq.sort
          # acrescenta à função de transição
          transicao << [ estado, el, 'q' + setas.join ]
        end
      end
    end

    # estado inicial
    i = [@atual.nome]
    @transicao.each do |funcao|
      if funcao[0] == @atual.nome and funcao[1] == nil
        i << funcao[2]
      end
    end
    inicial = 'q' + i.flatten.uniq.sort.join

    # estados finais
    finais = []
    estados.each do |estado|
      @finais.each do |final|
        finais << estado if estado.include? final
      end
    end
    finais.uniq!

    # simplifica, removendo os estados que não recebem nenhuma seta
    a_remover = []
    (estados - [inicial]).each do |estado|
      encontrado = false
      transicao.each do |funcao|
        encontrado = true if funcao[2] == estado
      end
      a_remover << estado if not encontrado
    end
    a_remover.each do |estado|
      estados.delete estado
      r = []
      transicao.each do |funcao|
        r << funcao if funcao[0] == estado
      end
      r.each { |x| transicao.delete x }
      finais.delete estado
    end

    return { K: estados, S: alfabeto, d: transicao, s: inicial, F: finais }
  end

  def gera_imagem!
    File.open('afnd.dot', 'w') do |f|
      f.puts 'digraph g {'
      f.puts '  rankdir=LR;'
      f.puts '  size="8,5"'
      f.puts '  node [shape = doublecircle]; ' + @finais.join(' ') + ';'
      f.puts '  node [shape = circle];'
      @estados.keys.each do |estado|
        @estados.keys.each do |destino|
          elems = []
          (@alfabeto + [nil]).each do |el|
            @transicao.each do |funcao|
              if funcao[0] == estado and funcao[1] == el and funcao[2].include? destino
                elems << (el == nil ? 'e' : el)
              end
            end
          end
          if elems.length > 0
            f.puts "  #{estado} -> #{destino} [ label = \"#{elems.uniq.sort.join(',')}\" ];"
          end
        end
      end
      f.puts '  null [shape = plaintext label=""];'
      f.puts "  null -> #{@atual.nome};"
      f.puts '}'
    end
    `dot afnd.dot -Tpng > afnd.png`
  end

end


#
# estados do AFD
#
class Estado
  attr_accessor :proximo, :final
  attr_reader :nome
  def initialize(nome)
    @nome = nome
    @proximo = {}
    @final = false
  end
end


#
# verifica os parâmetros
# 
if ARGV.length != 1 then
  puts <<EOS
Uso: afnd automato

Onde 'automato' é um autômato finito não-determinístico no seguinte formato:

M = {
  K: [ '1', '2', '3' ],           # lista de estados
  S: [ 'a', 'b' ],                # alfabeto
  d: [ [ '1', 'a', [] ],          # função de transição
       [ '1', 'b', ['2'] ],
       [ '1', nil, ['3'] ],
       [ '2', 'a', ['2','3'] ],
       [ '2', 'b', ['3'] ],
       [ '2', nil, [] ],
       [ '3', 'a', ['1'] ],
       [ '3', 'b', [] ],
       [ '3', nil, [] ],
     ],
  s: '1',                         # estado inicial
  F: [ '1' ]                      # estados finais
}
EOS
  exit 1
end

#
# carrega a máquina
#
begin
  $: << '.'
  require ARGV[0]
  raise 'Variável M não está setada.' if not defined? M
  @afnd = AFND.new(M)
  # converte o AFND
  print 'M = '
  pp @afnd.converte
  # gera imagem
rescue Exception => e
  puts "Autômato em formato inválido: #{e.message}"
  exit 1
end
@afnd.gera_imagem!
