#!/usr/bin/env lua

package.path = package.path .. ';./libchar/?.lua;./libchar/?.dll;./game/?.lua;./ui/?.lua'
require 'libchar/libchar'
require 'game'
require 'ui/map'

state = 'map'
colors = true

-- initialize screen
ch.init(80, 50, 'Fertile Crescent 0.1')
if colors then
   ch.bg('black')
else
   ch.bg('white')
end
ch.clear()
ch.flush()


-- initialize game
game = Game:new(100, 100, 'Assyria')

-- main loop
running = true
while running do
   if state == 'map' then
      map.draw()
      running = map.events()
   else
      error(_'Invalid state ' .. state)
   end
end

os.exit()
