set nocompatible

" movement with wrap
noremap  <buffer> <silent> k gk
noremap  <buffer> <silent> j gj
noremap  <buffer> <silent> 0 g0
noremap  <buffer> <silent> $ g$

" appearance
let g:solarized_italic = 0              " for colorized colorscheme
let g:solarized_bold = 0
let g:solarized_termcolors=256
set background=light
set guioptions=emgrt                    " GUI only screen resources
set hlsearch                            " incremental highlight search
set incsearch
set foldnestmax=1                       " max nesting
set synmaxcol=2048
filetype plugin indent on               " auto-load ident/syntax file
syntax on

" behaviour
set nobackup				" don't do backups
set nowrap                              " don't wrap
set encoding=utf-8                      " default encoding
set backspace=indent,eol,start          " backspace
if has('mouse')                         " activate mouse
  set mouse=a
endif
set autoindent                          " indent mode
autocmd FileType text setlocal textwidth=78
autocmd FileType tex  setlocal wrap lbr textwidth=0 colorcolumn=
autocmd BufReadPost * 
  \ if line("'\"") > 1 && line("'\"") <= line("$") |
  \   exe "normal! g`\"" |
  \ endif  " jump to last know position

" windows specific options
if has("gui_win32")                     " set font
  set guifont=Ubuntu_Mono:h10:cANSI    
  set clipboard=unnamed 
  set lines=50
endif
set keymodel=startsel,stopsel		" select with SHIFT

" status line
set ruler				" show position in file
set showcmd				" show command line
set history=100				" command line history

" language specific options
let c_hi_identifiers	= 'all'
let c_hi_libs	 = ['*'] 
let go_highlight_space_tab_error = 0
let go_highlight_trailing_whitespace_error = 0
set rtp+=C:/andre/desenv/go/misc/vim
au BufNewFile,BufRead *.cc set syntax=cpp11
au BufNewFile,BufRead *.h  set syntax=cpp11
au BufNewFile,BufRead,BufEnter *.cc,*.h set omnifunc=
let python_highlight_all = 1
let python_highlight_space_errors = 0

" fullscreen
nmap <silent> <M-f> :call libcallnr("gvimfullscreen.dll", "ToggleFullScreen", 0)<CR>

" testing
set guioptions=acg		" like text-mode
set laststatus=2		" status line black
set scrolloff=8			" start to scroll 8 lines away from to or bottom
set wildmenu			" better autocompletion
set fillchars="" 		" silly fillchars
nnoremap t <C-]>

" smart home
noremap <expr> <silent> <Home> col('.') == match(getline('.'),'\S')+1 ? '0' : '^'
imap <silent> <Home> <C-O><Home>

" define file type
function! Script()
	set ts=2
	set sw=2
	set sts=2
	set expandtab
endfunction
function! Compiled()
	set ts=8
	set sw=8
	set sts=8
	set noexpandtab
endfunction

" correct CTRL-PGUP/DOWN in rxvt
nmap <ESC>[5^ <C-PageUp>
nmap <ESC>[6^ <C-PageDown>
nmap <ESC><ESC>[5^ <C-PageUp>
nmap <ESC><ESC>[6^ <C-PageDown>
imap <ESC>[5^ <C-PageUp>
imap <ESC>[6^ <C-PageDown>
imap <ESC><ESC>[5^ <C-PageUp>
imap <ESC><ESC>[6^ <C-PageDown>

" 256 colors
set t_Co=256

" move cursor inside a paragraph
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
nnoremap <Down> gj
nnoremap <Up> gk
vnoremap <Down> gj
vnoremap <Up> gk
inoremap <Down> <C-o>gj
inoremap <Up> <C-o>gk

" mark 80th column
set textwidth=80
set colorcolumn=+1

" clipboard
set clipboard=unnamed

" clang-complete options
let g:clang_complete_auto=0
let g:clang_close_preview=1
let g:clang_user_options = '-std=c++11'
set wildmode=longest,list:longest
inoremap <expr> <Esc>      pumvisible() ? "\<C-e>" : "\<Esc>"
inoremap <expr> <CR>       pumvisible() ? "\<C-y>" : "\<CR>"
inoremap <expr> <Tab>       pumvisible() ? "\<C-y>" : "\<Tab>"
inoremap <expr> <Down>     pumvisible() ? "\<C-n>" : "\<Down>"
inoremap <expr> <Up>       pumvisible() ? "\<C-p>" : "\<Up>"
inoremap <expr> <PageDown> pumvisible() ? "\<PageDown>\<C-p>\<C-n>" : "\<PageDown>"
inoremap <expr> <PageUp>   pumvisible() ? "\<PageUp>\<C-p>\<C-n>" : "\<PageUp>"
inoremap <C-l> <C-x><C-u>
"set conceallevel=2
"set concealcursor=vin
"let g:clang_snippets=1
"let g:clang_conceal_snippets=1
"let g:clang_snippets_engine='clang_complete'
set completeopt=menu,menuone
