#!/bin/sh
#
# ~/.xinitrc
#
#Executed by startx (run your window manager from here)

/usr/bin/VBoxClient-all

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

setxkbmap br
xmodmap ~/.Xmodmap
xrdb ~/.Xresources
feh --bg-center ~/wpaper/montanhas.jpg
conky

#sudo cpupower frequency-set -g performance

#exec wmaker
exec i3
#exec startxfce4

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
