#INCLUDES=
#LIBS=-lncurses -llua -lm
INCLUDES=-IC:\andre\desenv\lua\include
LIBS=-LC:\andre\desenv\lua -llua5.1

all:
	gcc -g -Wall -o fccacurses fccacurses.c $(INCLUDES) $(LIBS)

clean:
	rm fccacurses
